package org.daveo.exception;

public class UserNotFoundException extends RuntimeException {
}
